[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=16384
    -DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    gilmaimon/ArduinoWebsockets @ ^0.5.4
    marian-craciunescu/ESP32Ping @ ^1.7
